apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dv-app-set
spec:
  generators:
    - git:
        repoURL: https://github.com/rotemjac/argocd-app-of-apps
        revision: HEAD
        files:
          - path: "dv-multi-deployments/app-set-file-generator-with-crossplane/cluster-config/**/*.json"
  template:
    metadata:
      name: 'dv-{{tenant.name}}'
    spec:
      project: divvy-multi-deployments-with-infra
      source:
        repoURL: http://alcide-argo-test.s3-website-us-east-1.amazonaws.com/databases
        chart: divvy-argo-with-crossplace
        targetRevision: 1.13.0
        helm:
          parameters:
            - name: postfix
              value: '{{tenant.name}}'
            - name: divvy_cloud.source.namespace
              value: argocd
            - name: divvy_cloud.source.project
              value: divvy-multi-deployments-with-infra
            - name: divvy_cloud.source.repoURL
              value: http://alcide-argo-test.s3-website-us-east-1.amazonaws.com/alcide
            - name: divvy_cloud.source.chart.name
              value: divvycloud
            - name: divvy_cloud.source.chart.version
              value: '{{tenant.source.chart.version}}'

            - name: divvy_cloud.destination.namespace
              value: '{{tenant.name}}-ns'
            - name: divvy_cloud.destination.server
              value: '{{local_server}}' # TODO: Notice that this was changed from {{url}}

            - name: infra.vpc.name
              value: '{{infra.vpc_name}}'

        #repoURL: https://github.com/rotemjac/argocd-app-of-app
        #targetRevision: HEAD
        #path: "dv-multi-deployments/app-set-file-generator-with-crossplane/stack"

      destination:
        server: '{{local_server}}'
        namespace: '{{tenant.name}}-ns'