namespace : argocd
project: divvycloud

divvy_cloud:
  repoURL: http://alcide-argo-test.s3-website-us-east-1.amazonaws.com/alcide
  destination:
    namespace: divvy-test2
    server: https://kubernetes.default.svc