apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cassandra
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.databases.destination.namespace }}
    server: {{ .Values.databases.destination.server }}
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.databases.repoURL }}
    chart: cassandra
    targetRevision: 7.5.0