namespace : argocd
project: alcide-databases


databases:
  repoURL: http://alcide-helm-repo-db-charts.s3-website-us-east-1.amazonaws.com/stable
  destination:
    namespace: databases
    server: https://kubernetes.default.svc

ops:
  repoURL: http://alcide-helm-repo-db-charts.s3-website-us-east-1.amazonaws.com/ops
  destination:
    namespace: ops
    server: https://kubernetes.default.svc