namespace : argocd
spec:
  project: alcide-databases
  destination:
    namespace : argocd
    server: https://kubernetes.default.svc
  repoURL: http://alcide-helm-repo-db-charts.s3-website-us-east-1.amazonaws.com/stable