namespace : argocd
project: alcide-vault-plugin-test

databases:
  repoURL: http://alcide-argo-test.s3-website-us-east-1.amazonaws.com/databases
  destination:
    namespace: databases
    server: https://kubernetes.default.svc

ops:
  repoURL: http://alcide-argo-test.s3-website-us-east-1.amazonaws.com/ops
  destination:
    namespace: ops
    server: https://kubernetes.default.svc


alcide:
  repoURL: http://alcide-argo-test.s3-website-us-east-1.amazonaws.com/alcide
  destination:
    namespace: alcide
    server: https://kubernetes.default.svc


aws_test:
  repoURL: https://gitlab.com/rotemjac/argo-cd.git
  path: test
  destination:
    namespace: alcide-vault-plugin-test
    server: https://kubernetes.default.svc