namespace : argocd
project: alcide-databases


databases:
  repoURL: http://alcide-argo-test.s3-website-us-east-1.amazonaws.com/databases
  destination:
    namespace: databases
    server: https://kubernetes.default.svc

ops:
  repoURL: http://alcide-argo-test.s3-website-us-east-1.amazonaws.com/ops
  destination:
    namespace: ops
    server: https://kubernetes.default.svc