apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dv-dep
spec:
  generators:
    - list:
        elements:
        - cluster: tenant-1
          url: { { .Values.destination.server } }
        - cluster: tenant-2
          url: { { .Values.destination.server } }
  template:
    metadata:
      name: 'dv-{{cluster}}'
    spec:
      project: {{ .Values.project }}
      source:
        repoURL: {{ .Values.repoURL }}
        chart: divvycloud
        targetRevision: 18.0.1
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}'