apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dv-dep
spec:
  generators:
  - list:
      items:
      - tenant: tenant-1
      - tenant: tenant-2
  template:
    metadata:
      name: 'dv-'
    spec:
      project: {{ .Values.project }}
      source:
        repoURL: {{ .Values.repoURL }}
        chart: divvycloud
        targetRevision: 18.0.1
      destination:
        server: { { .Values.destination.server } }
        namespace: '{{tenant}}'