apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-secret-manager
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.aws_test.destination.namespace }}
    server: {{ .Values.aws_test.destination.server }}
  project: {{ .Values.project }}
  source:
    path: test
    plugin:
      name: argocd-vault-plugin
    repoURL: {{ .Values.aws_test.repoURL }}
    targetRevision: HEAD