apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: divvy-cloud
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.divvy_cloud.destination.namespace }}
    server: {{ .Values.divvy_cloud.destination.server }}
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.divvy_cloud.repoURL }}
    chart: divvycloud
    targetRevision: 18.0.1